### ISSUE TITLE
Global style loading method

### ISSUE THREAD

**Issue by anightwithmrwonderful** [moxystudio/react-app-rewire-css-modules-extensionless#3]
Hi, I'm curious if this plugin can also load global styles (without having to wrap selectors with :global(*) in a CSS module file)? If so, I'd really like to know how it does this? Aka., how can you test for / differentiate between the following:

CSS module:
`import styles from './style.css'`

Global style:
`import './style.css'`

I apologize if this addresses features not encapsulated by your library. In many ways this is a feature request (could be cool to add to the roadmap). Also, it would be fantastic if this plugin played well with react-app-rewire-preload-plugin, as to create several CSS bundles and load them in from the server as needed (another feature request).

Thanks for taking the time to reading this over!

**Comment by harrysolovay** [comment]
I accidentally filed this issue when logged into a client's GitHub account. I'm the "filer" of the issue. I'd love to know what you're thinking in terms of how these features could be implemented. Thank you!

**Comment by satazor** [comment]
Hello! 

This package can’t detect based on if you use the styles or not. Nevertheless, by default, this plugin will only apply css modules for files in your `src/`. 

You may tweak this behavior with the `include` and `exclude` options.

**Comment by satazor** [comment]
Regarding the preload plugin, I don’t use it and I would need to investigate why it’s not working correctly. If you have that use case, it would be cool if you could investigate.

**Comment by harrysolovay** [comment]
I don't think that CSS splitting is something that would make sense built into this library (that would make the focus of the library about SSR or static site generation). Still it's good to think about :) Thank you for your quick response.

I'm gonna go ahead and close this issue.
