### ISSUE TITLE
Css Modules Server Side Rendering

### ISSUE THREAD

**Issue by eman1000** [moxystudio/react-app-rewire-css-modules-extensionless#6]
Hi,
 How can i make css modules load on server side rendering. Right now it like the class name is being removed
 
module.exports = function override(config, env){
   config = require('react-app-rewire-css-modules-extensionless').webpack(config, env,{
    localIdentName: '[local]___[hash:base64:5]',
    exclude : /styles/
   });

  return config
}

**Comment by satazor** [comment]
This module is specific to create react app, which doesn’t support server side rendering.

Can you elaborate what you are trying to do with this module?

**Comment by satazor** [comment]
Closing as invalid.
